<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'6Kej5Yaz5pa55qGI');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB');
$cfg_Cs[3]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[4]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[5]=array(0,1,0,'6aaW6aG16L2u5pKt5Zu+');
$cfg_Cs[6]=array(0,1,0,'5ZCI5L2c5LyZ5Ly0');
$cfg_Cs[7]=array(0,1,0,'572R56uZTE9HTw==');
$cfg_Cs[8]=array(0,1,0,'6IGU57O75oiR5Lus5Zu+54mH');
$cfg_Cs[9]=array(0,1,0,'5YWs5Y+45qaC5Ya15Zu+54mH');
$cfg_Cs[10]=array(0,1,0,'5YWs5Y+45LqM57u056CB5Zu+54mH');
?>