<?php
$z[0]=Array("global","",42,68);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("id","",87,98);
$z[2]=Array("title","",108,122);
$z[3]=Array("litpic","",134,149);
$z[4]=Array("global","",219,245);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("id","",264,275);
$z[6]=Array("title","",285,299);
$z[7]=Array("title","",301,315);
$z[8]=Array("description","",341,391);
$z[8][4]['function']="cn_substr(@me,240)";
$z[9]=Array("global","",406,432);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("id","",451,462);

?>