<?php
$z[0]=Array("global","",87,112);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("fieldname:typeid","",131,155);
$z[2]=Array("field","",166,195);
$z[2][4]['name']="typename";
$z[3]=Array("field","",197,226);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n          <li><a href=\"{dede:global.cfg_cmsurl/}/plus/list.php?tid=1\">[field:typename/]</a></li>\r\n          ",283,446);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>