<li class="mainlevel" id="mainlevel_0[field:global.autoindex/]" >
        <p><a href="{dede:field name='typeurl'/}"  title="{dede:field name='typename'/}">{dede:field name='typename'/}</a>
        <ul id="sub_01" class="menual">
          {dede:channel type='son' noself='yes'}
          <li><a href="{dede:global.cfg_cmsurl/}/plus/list.php?tid=1">[field:typename/]</a></li>
          {/dede:channel}
        </ul>
        </p>
      </li>