<?php
$z[0]=Array("arclist","\r\n    background-image: url([field:litpic/]);\r\n    ",75,171);
$z[0][4]['row']="1";
$z[0][4]['typeid']="10";
$z[1]=Array("flink","[field:link /]",313,387);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="10";
$z[1][4]['type']="text";
$z[2]=Array("channel","\r\n        \r\n        ·<a href=\"[field:typeurl/]\"  title=\"[field:typename/]\">[field:typename/]</a> ",544,682);
$z[2][4]['type']="top";
$z[3]=Array("global","",726,752);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",778,802);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",835,857);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",883,908);
$z[6][4]['name']="cfg_mobile";
$z[7]=Array("global","",938,964);
$z[7][4]['name']="cfg_address";
$z[8]=Array("global","",1186,1211);
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("global","",1445,1470);
$z[9][4]['name']="cfg_cmsurl";

?>