<?php
$z[0]=Array("global","",77,98);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",114,135);
$z[1][4]['name']="cfg_sj";
$z[2]=Array("arclist","<img src=\"[field:litpic/]\" width=\"397\" height=\"110\" />",213,311);
$z[2][4]['row']="1";
$z[2][4]['typeid']="7";
$z[3]=Array("global","",413,438);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channelartlist","\r\n      <li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\" >\r\n        <p><a href=\"{dede:global.cfg_cmsurl/}/plus/list.php?tid={dede:field name='id'/}\"\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <ul id=\"sub_01\" class=\"menual\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"{dede:global.cfg_cmsurl/}/plus/list.php?tid=1\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n        </p>\r\n      </li>\r\n      ",503,1062);
$z[4][4]['typeid']="top";
$z[5]=Array("arclist","\r\n      <li><img src=\"[field:litpic/]\"  alt=\"[field:title/]\" title=\"[field:title/]\" width=\"1900\" height=\"565\"/></li>\r\n      ",1185,1353);
$z[5][4]['row']="2";
$z[5][4]['typeid']="5";

?>